In [ ]:
# Steven Swanson
# svm.ipynb
# Implementation of Support Vector Machine supervised learning algorithm on iris dataset

In [2]:
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import IPython
import sklearn

In [3]:
# Iris Dataset that is already included in the scikit-learn datasets module

# Load Iris Dataset
from sklearn.datasets import load_iris
iris_dataset = load_iris()

print("First five rows of data:\n{}".format(iris_dataset['data'][:5]))

First five rows of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [4]:
# train_test_split function
    # 80% of the rows will be the training set
    # 20% of the rows become the test set
    # Data is randomly shuffled before it is split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], test_size = 0.2, random_state=2)

In [5]:
# Train the algorithm
from sklearn.svm import SVC
svclassifier = SVC(kernel = 'linear')
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [7]:
# Predicting Classes
y_pred = svclassifier.predict(X_test)
print(y_pred)

[0 0 2 0 0 2 0 2 2 0 0 0 0 0 1 1 0 1 2 1 1 1 2 1 1 0 0 2 0 2]


In [8]:
# Evaluate the model
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [9]:
print("Accuracy on training set: {:.3f}".format(svclassifier.score(X_train, y_train)))
print("Accuracy on test set: {:.3f}".format(svclassifier.score(X_test, y_test)))

Accuracy on training set: 0.992
Accuracy on test set: 1.000


In [10]:
# Train the algorithm
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train)

SVC()

In [11]:
print("Accuracy on training set: {:.3f}".format(svc.score(X_train, y_train)))
print("Accuracy on test set: {:.3f}".format(svc.score(X_test, y_test)))

Accuracy on training set: 0.975
Accuracy on test set: 0.967
